import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import type { ReviewItem } from "../review";
import { BriefText } from "../brief-text";

export const Route=createFileRoute('/')({component:Dashboard});
type Run={id:string;started_at:string;finished_at:string|null;status:string;detail:string;processed:number};
type Brief={id:string;run_id:string|null;title:string;body:string;created_at:string};
type Event={id:number;run_id:string|null;key:string;action:string;state:string;detail:string;created_at:string};
type Snapshot={answers:{key:string;answer:string;answered_at:string}[];items:ReviewItem[];briefs:Brief[];events:Event[];csrf:string;schedule:string;accounts:{email:string}[];counts:{email:string;inboxUnread:number;remaining:boolean}[];runs:Run[];undo:{key:string;state:string}[];message:string|null};
const date=(iso:string)=>new Date(iso).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const mailLink=(key:string)=>'/gmail?key='+encodeURIComponent(key);
function Dashboard(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('brief'),[selected,setSelected]=useState<string[]>([]),[account,setAccount]=useState('all'),[run,setRun]=useState('all'),[briefId,setBriefId]=useState('');
 async function refresh(){const r=await fetch('/api/review');if(!r.ok)throw Error(r.status===403?'Your session expired. Reopen your private dashboard link.':'Could not load the review.');setData(await r.json() as Snapshot);}
 useEffect(()=>{void refresh().catch(e=>setError((e as Error).message));const timer=setInterval(()=>void refresh().catch(()=>{}),30000);return()=>clearInterval(timer);},[]);
 async function action(action:'reviewed'|'archive'|'undo',keys:string[]){
  if(!data||!keys.length)return;setBusy(true);setNotice('');
  try{const results:{ok:boolean;message:string}[]=[];for(let i=0;i<keys.length;i+=50){const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,keys:keys.slice(i,i+50),csrf:data.csrf})});if(!r.ok)throw Error('Action interrupted. Refresh to see completed changes.');results.push(...await r.json() as {ok:boolean;message:string}[]);}
   setNotice(`${results.filter(x=>x.ok).length} of ${results.length} saved.${results.some(x=>!x.ok)?' Some changes could not be confirmed.':''}`);setSelected([]);await refresh();
  }catch(e){setNotice((e as Error).message);}finally{setBusy(false);}
 }
 const items=data?.items??[],questions=items.filter(x=>x.category==='attention'&&x.status==='pending'&&(account==='all'||x.email===account));
 const briefs=data?.briefs??[],brief=briefs.find(x=>x.id===briefId)??briefs[0];
 const last=data?.runs[0];
 const byKey=new Map(items.map(item=>[item.key,item]));
 const events=(data?.events??[]).filter(e=>(run==='all'||e.run_id===run)&&(account==='all'||byKey.get(e.key)?.email===account));
 const history=items.filter(x=>x.status!=='pending'&&(account==='all'||x.email===account));
 const selectable=(tab==='questions'?questions:tab==='history'?history:[]).filter(x=>!['archived','archiving','uncertain'].includes(x.status));
 return <main><header><a className="brand" href="/">mini me<span> / daily</span></a><a className="subtle-link" href="/accounts">Manage accounts ↗</a></header>
  <section className="hero"><div><div className="eyebrow">A LITTLE ORDER. A LITTLE DISCOVERY.</div><h1>Your inbox,<br/><em>with a head start.</em></h1><p>Read and act in Gmail. Catch up with me here.</p></div><aside className="schedule"><span className="dot"/>{data?.schedule??'Loading…'}<small>{data?.accounts.length??0} mailboxes connected</small><small>{last?`Latest review: ${date(last.started_at)} PT · ${last.status}`:'Your first brief is on its way.'}</small></aside></section>
  {error&&<p className="notice" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
  {last?.status==='running'&&<p className="coverage">A review is underway. Confirmed actions appear in the run log as they happen.</p>}
  {(data?.counts.some(x=>x.remaining)||items.some(x=>x.status==='pending'&&x.summary==='Awaiting personal review.'))&&<p className="coverage">The initial backlog is still being reviewed. Each brief reports its actual coverage.</p>}
  <details className="gmail-shortcuts"><summary>Your Gmail inboxes & labels</summary><section className="gmail-shelf" aria-label="Your Gmail inboxes">{data?.accounts.map(a=><div key={a.email}><a className="gmail-inbox" href={'/gmail?email='+encodeURIComponent(a.email)} target="_blank" rel="noreferrer">{a.email} ↗</a><div className="gmail-tags">{['Read','Action','Records','Updates','Waiting'].map(label=><a key={label} href={'/gmail?email='+encodeURIComponent(a.email)+'&label='+encodeURIComponent('Mini-me/'+label)} target="_blank" rel="noreferrer">{label}</a>)}</div></div>)}</section></details>
  <div className="toolbar"><nav aria-label="Review sections">{[{id:'brief',name:'Daily brief'},{id:'questions',name:'Questions'},{id:'log',name:'Run log'},{id:'history',name:'Archive & history'}].map(t=><button key={t.id} className={tab===t.id?'tab active':'tab'} onClick={()=>{setTab(t.id);setSelected([]);}}>{t.name}{t.id==='questions'&&<span>{questions.length}</span>}</button>)}</nav>{tab!=='brief'&&<select aria-label="Mailbox" value={account} onChange={e=>{setAccount(e.target.value);setSelected([]);}}><option value="all">All mailboxes</option>{data?.accounts.map(a=><option key={a.email}>{a.email}</option>)}</select>}</div>
  {tab==='brief'&&<section className="daily-brief"><div className="section-title"><h2>Daily brief</h2>{briefs.length>1&&<select aria-label="Past briefs" value={brief?.id??''} onChange={e=>setBriefId(e.target.value)}>{briefs.map(b=><option key={b.id} value={b.id}>{date(b.created_at)} · {b.title}</option>)}</select>}</div>{brief?<article className="brief-paper"><div className="eyebrow">{date(brief.created_at)} PT</div><h2>{brief.title}</h2><BriefText text={brief.body}/>{brief.run_id&&<button onClick={()=>{setRun(brief.run_id!);setTab('log');}}>See this run’s log</button>}</article>:<div className="empty"><h3>Your first dispatch is brewing.</h3><p>A useful recap, a few good finds when there are any, and only real questions. No filler required.</p></div>}</section>}
  {tab==='log'&&<section><div className="section-title"><div><h2>Run log</h2><p>Confirmed actions, unresolved outcomes, and the reasons behind them.</p></div><select aria-label="Review run" value={run} onChange={e=>setRun(e.target.value)}><option value="all">All runs and manual actions</option>{data?.runs.map(r=><option key={r.id} value={r.id}>{date(r.started_at)} · {r.status}</option>)}</select></div><div className="run-summaries">{data?.runs.filter(r=>run==='all'||r.id===run).map(r=><details key={r.id}><summary>{date(r.started_at)} · {r.status} · {r.processed} reviewed</summary><p>{r.detail}</p></details>)}</div>{!events.length&&<p className="empty">No action events recorded for this selection. Older cleanup is available in Archive & history.</p>}<ol className="event-log">{events.map(e=>{const item=byKey.get(e.key);return <li key={e.id}><div className="card-meta"><span>{e.action} · {e.state}</span><time>{date(e.created_at)} PT</time></div><h3>{item?<a href={mailLink(e.key)} target="_blank" rel="noreferrer">{item.subject} ↗</a>:e.action}</h3><p>{e.detail}</p><small>{item?.email}</small></li>;})}</ol></section>}
  {(tab==='questions'||tab==='history')&&<section><div className="section-title"><div><h2>{tab==='questions'?'Questions':'Archive & history'}</h2><p>{tab==='questions'?'Only what needs your judgment. Answers help me learn.':'Past decisions and a way to bring archived mail back.'}</p></div>{selectable.length>0&&<div className="batch"><label><input type="checkbox" checked={selectable.every(x=>selected.includes(x.key))} onChange={e=>setSelected(e.target.checked?selectable.map(x=>x.key):[])}/> Select all</label><button className="primary" disabled={busy||!selected.length} onClick={()=>void action('archive',selected)}>Archive selected ({selected.length})</button></div>}</div><div className="cards">{(tab==='questions'?questions:history).map(item=><article className="card" key={item.key}><div className="card-meta"><span>{item.status==='following_up'?'I’m following up':item.status}</span><time>{date(item.receivedAt)} PT</time></div><div className="card-heading">{selectable.some(x=>x.key===item.key)&&<input type="checkbox" aria-label={`Select ${item.subject}`} checked={selected.includes(item.key)} disabled={busy} onChange={e=>setSelected(v=>e.target.checked?[...v,item.key]:v.filter(k=>k!==item.key))}/>}<h3>{item.subject}</h3></div>{tab==='history'&&item.category==='attention'?<><p className="summary">Question closed. No answer needed.</p><details className="past-question"><summary>Past question and context</summary><p>{item.summary}</p><p>{item.reason}</p></details></>:<><p className="summary">{item.summary}</p><p className="reason">{item.reason}</p></>}<div className="source"><span>{item.email}</span><a href={mailLink(item.key)} target="_blank" rel="noreferrer">Open in Gmail ↗</a></div>{tab==='questions'&&data&&<Answer itemKey={item.key} csrf={data.csrf} onSaved={refresh}/>}<div className="card-actions">{tab==='questions'&&<button disabled={busy} onClick={()=>void action('reviewed',[item.key])}>Already handled</button>}{data?.undo.some(x=>x.key===item.key&&['archived','uncertain'].includes(x.state))&&<button disabled={busy} onClick={()=>void action('undo',[item.key])}>Restore to inbox</button>}</div></article>)}</div>{!(tab==='questions'?questions:history).length&&<div className="empty">{tab==='questions'?'Nothing I need to ask right now.':'No history for this mailbox yet.'}</div>}</section>}
  <footer>Organized in Gmail. Explained here. <span>Unread state stays yours. Archives can be restored.</span></footer>
 </main>;
}

function Answer({itemKey,csrf,onSaved}:{itemKey:string;csrf:string;onSaved:()=>Promise<void>}){
 const [answer,setAnswer]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 return <form className="answer-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{const response=await fetch('/api/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:itemKey,csrf,answer})});if(!response.ok)throw Error('Could not save your answer.');await onSaved();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>
 <label>Your answer<textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={2} maxLength={8000} placeholder="Tell me once. I’ll remember." required/></label><button className="primary" disabled={saving||!answer.trim()}>Save answer</button>{error&&<p role="alert">{error}</p>}
 </form>;
}
